# Generated by Django 5.2.13 on 2026-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_pelicula_delete_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pelicula",
            name="director",
        ),
        migrations.RemoveField(
            model_name="pelicula",
            name="fecha_estreno",
        ),
        migrations.AddField(
            model_name="pelicula",
            name="anio",
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pelicula",
            name="duracion",
            field=models.IntegerField(default=120, help_text="Duración en minutos"),
            preserve_default=False,
        ),
    ]
