# Generated by Django 5.2.13 on 2026-05-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_pelicula_director_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="duracion",
            field=models.CharField(max_length=50),
        ),
    ]
