# Generated by Django 5.2.13 on 2026-05-17 10:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_pelicula_duracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
