# Generated by Django 5.2.13 on 2026-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_pelicula_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pelicula",
            name="fecha_creacion",
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="imagen",
            field=models.ImageField(upload_to="peliculas/"),
        ),
    ]
