# Generated by Django 5.2.13 on 2026-05-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_pelicula_fecha_creacion_alter_pelicula_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="peliculas/"),
        ),
    ]
