# Generated by Django 5.2.13 on 2026-05-18 02:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_pelicula_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
